# Generated by Django 5.1.6 on 2025-02-05 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('peso', models.FloatField()),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fazenda.especie')),
            ],
        ),
    ]
